export const DSKP_DATA: Record<string, { unit: string; standardContent: string; value: string }[]> = {
  "Tahun 1": [
    { unit: "Unit 1: Pegangan Hidup Saya", standardContent: "1.0 Kepercayaan kepada Tuhan", value: "Kepercayaan kepada Tuhan" },
    { unit: "Unit 2: Baik Hati", standardContent: "2.0 Bantuan Kepada Diri Sendiri", value: "Baik Hati" },
    { unit: "Unit 3: Tanggungjawab Diri", standardContent: "3.0 Tanggungjawab Terhadap Diri Sendiri", value: "Bertanggungjawab" },
    { unit: "Unit 4: Terima Kasih", standardContent: "4.0 Berterima Kasih Terhadap Diri Sendiri", value: "Berterima Kasih" },
    { unit: "Unit 5: Budi Bahasa", standardContent: "5.0 Hemah Tinggi Dalam Kehidupan Seharian", value: "Hemah Tinggi" },
    { unit: "Unit 6: Hormat", standardContent: "6.0 Hormat Terhadap Diri Sendiri", value: "Hormat" },
    { unit: "Unit 7: Sayangi Diri", standardContent: "7.0 Sayangi Diri Sendiri", value: "Kasih Sayang" },
    { unit: "Unit 8: Adil", standardContent: "8.0 Keadilan Dalam Kehidupan Seharian", value: "Keadilan" },
    { unit: "Unit 9: Berani", standardContent: "9.0 Keberanian Dalam Kehidupan Seharian", value: "Keberanian" },
    { unit: "Unit 10: Jujur", standardContent: "10.0 Kejujuran Dalam Kehidupan Seharian", value: "Kejujuran" },
    { unit: "Unit 11: Rajin", standardContent: "11.0 Kerajinan Dalam Kehidupan Seharian", value: "Kerajinan" },
    { unit: "Unit 12: Kerjasama", standardContent: "12.0 Kerjasama Dalam Kehidupan Seharian", value: "Kerjasama" },
    { unit: "Unit 13: Kesederhanaan", standardContent: "13.0 Kesederhanaan Dalam Kehidupan Seharian", value: "Kesederhanaan" },
    { unit: "Unit 14: Toleransi", standardContent: "14.0 Toleransi Dalam Kehidupan Seharian", value: "Toleransi" }
  ],
  "Tahun 2": [
    { unit: "Unit 1: Pegangan Agama Keluarga", standardContent: "1.0 Kepatuhan Kepada Ajaran Agama Dalam Keluarga", value: "Kepercayaan kepada Tuhan" },
    { unit: "Unit 2: Baik Hati Terhadap Keluarga", standardContent: "2.0 Bantuan Kepada Keluarga", value: "Baik Hati" },
    { unit: "Unit 3: Tanggungjawab Terhadap Keluarga", standardContent: "3.0 Tanggungjawab Terhadap Keluarga", value: "Bertanggungjawab" },
    { unit: "Unit 4: Terima Kasih Terhadap Keluarga", standardContent: "4.0 Berterima Kasih Terhadap Keluarga", value: "Berterima Kasih" },
    { unit: "Unit 5: Hemah Tinggi Dalam Keluarga", standardContent: "5.0 Hemah Tinggi Dalam Keluarga", value: "Hemah Tinggi" },
    { unit: "Unit 6: Hormat Kepada Ahli Keluarga", standardContent: "6.0 Hormat Kepada Ahli Keluarga", value: "Hormat" },
    { unit: "Unit 7: Sayangi Ahli Keluarga", standardContent: "7.0 Sayangi Ahli Keluarga", value: "Kasih Sayang" },
    { unit: "Unit 8: Adil Kepada Keluarga", standardContent: "8.0 Keadilan Kepada Keluarga", value: "Keadilan" },
    { unit: "Unit 9: Berani Mempertahankan Maruah Keluarga", standardContent: "9.0 Keberanian Mempertahankan Maruah Keluarga", value: "Keberanian" },
    { unit: "Unit 10: Jujur Terhadap Ahli Keluarga", standardContent: "10.0 Kejujuran Terhadap Ahli Keluarga", value: "Kejujuran" },
    { unit: "Unit 11: Rajin Terhadap Ahli Keluarga", standardContent: "11.0 Kerajinan Terhadap Ahli Keluarga", value: "Kerajinan" },
    { unit: "Unit 12: Kerjasama Dalam Keluarga", standardContent: "12.0 Kerjasama Dalam Keluarga", value: "Kerjasama" },
    { unit: "Unit 13: Kesederhanaan Dalam Keluarga", standardContent: "13.0 Kesederhanaan Dalam Keluarga", value: "Kesederhanaan" },
    { unit: "Unit 14: Toleransi Sesama Ahli Keluarga", standardContent: "14.0 Toleransi Sesama Ahli Keluarga", value: "Toleransi" }
  ],
  "Tahun 3": [
    { unit: "Unit 1: Amalan Ajaran Agama di Sekolah", standardContent: "1.0 Amalan Ajaran Agama atau Kepercayaan di Sekolah", value: "Kepercayaan kepada Tuhan" },
    { unit: "Unit 2: Bantuan Kepada Warga Sekolah", standardContent: "2.0 Bantuan Kepada Warga Sekolah", value: "Baik Hati" },
    { unit: "Unit 3: Tanggungjawab di Sekolah", standardContent: "3.0 Tanggungjawab di Sekolah", value: "Bertanggungjawab" },
    { unit: "Unit 4: Amalan Berterima Kasih di Sekolah", standardContent: "4.0 Amalan Berterima Kasih di Sekolah", value: "Berterima Kasih" },
    { unit: "Unit 5: Beradab Sopan di Sekolah", standardContent: "5.0 Beradab Sopan dan Berbudi Pekerti Mulia di Sekolah", value: "Hemah Tinggi" },
    { unit: "Unit 6: Hormat Kepada Warga Sekolah", standardContent: "6.0 Hormat Kepada Warga Sekolah dan Pelawat", value: "Hormat" },
    { unit: "Unit 7: Sayangi Sekolah", standardContent: "7.0 Sayangi Sekolah dan Warga Sekolah", value: "Kasih Sayang" },
    { unit: "Unit 8: Sikap Adil di Sekolah", standardContent: "8.0 Sikap Adil di Sekolah", value: "Keadilan" },
    { unit: "Unit 9: Berani Menghadapi Cabaran di Sekolah", standardContent: "9.0 Berani Menghadapi Cabaran di Sekolah", value: "Keberanian" },
    { unit: "Unit 10: Jujur di Sekolah", standardContent: "10.0 Jujur di Sekolah", value: "Kejujuran" },
    { unit: "Unit 11: Rajin di Sekolah", standardContent: "11.0 Rajin di Sekolah", value: "Kerajinan" },
    { unit: "Unit 12: Kerjasama di Sekolah", standardContent: "12.0 Kerjasama di Sekolah", value: "Kerjasama" },
    { unit: "Unit 13: Kesederhanaan di Sekolah", standardContent: "13.0 Kesederhanaan di Sekolah", value: "Kesederhanaan" },
    { unit: "Unit 14: Toleransi di Sekolah", standardContent: "14.0 Toleransi di Sekolah", value: "Toleransi" }
  ],
  "Tahun 4": [
    { unit: "Unit 1: Amalan Ajaran Agama Mengeratkan Hubungan Jiran", standardContent: "1.0 Amalan Ajaran Agama atau Kepercayaan Mengeratkan Hubungan Sesama Jiran", value: "Kepercayaan kepada Tuhan" },
    { unit: "Unit 2: Prihatin Terhadap Keperluan Jiran", standardContent: "2.0 Prihatin Terhadap Keperluan dan Kebajikan Jiran", value: "Baik Hati" },
    { unit: "Unit 3: Tanggungjawab Terhadap Jiran", standardContent: "3.0 Tanggungjawab Terhadap Jiran", value: "Bertanggungjawab" },
    { unit: "Unit 4: Berterima Kasih Terhadap Jiran", standardContent: "4.0 Berterima Kasih Terhadap Jiran", value: "Berterima Kasih" },
    { unit: "Unit 5: Beradab Sopan Terhadap Jiran", standardContent: "5.0 Beradab Sopan dan Berbudi Pekerti Mulia Terhadap Jiran", value: "Hemah Tinggi" },
    { unit: "Unit 6: Menghormati Jiran", standardContent: "6.0 Menghormati Jiran", value: "Hormat" },
    { unit: "Unit 7: Menyayangi Jiran", standardContent: "7.0 Menyayangi Jiran", value: "Kasih Sayang" },
    { unit: "Unit 8: Bersikap Adil Terhadap Jiran", standardContent: "8.0 Bersikap Adil Terhadap Jiran", value: "Keadilan" },
    { unit: "Unit 9: Berani Terhadap Jiran", standardContent: "9.0 Berani Terhadap Jiran", value: "Keberanian" },
    { unit: "Unit 10: Jujur Terhadap Jiran", standardContent: "10.0 Jujur Terhadap Jiran", value: "Kejujuran" },
    { unit: "Unit 11: Rajin Terhadap Jiran", standardContent: "11.0 Rajin Terhadap Jiran", value: "Kerajinan" },
    { unit: "Unit 12: Kerjasama Dengan Jiran", standardContent: "12.0 Kerjasama Dengan Jiran", value: "Kerjasama" },
    { unit: "Unit 13: Kesederhanaan Sesama Jiran", standardContent: "13.0 Kesederhanaan Sesama Jiran", value: "Kesederhanaan" },
    { unit: "Unit 14: Toleransi Sesama Jiran", standardContent: "14.0 Toleransi Sesama Jiran", value: "Toleransi" }
  ],
  "Tahun 5": [
    { unit: "Unit 1: Amalan Ajaran Agama dalam Masyarakat", standardContent: "1.0 Amalan Ajaran Agama atau Kepercayaan dalam Masyarakat", value: "Kepercayaan kepada Tuhan" },
    { unit: "Unit 2: Bantuan Kepada Masyarakat", standardContent: "2.0 Bantuan Kepada Masyarakat", value: "Baik Hati" },
    { unit: "Unit 3: Tanggungjawab Terhadap Masyarakat", standardContent: "3.0 Tanggungjawab Terhadap Masyarakat", value: "Bertanggungjawab" },
    { unit: "Unit 4: Amalan Berterima Kasih dalam Masyarakat", standardContent: "4.0 Amalan Berterima Kasih dalam Masyarakat", value: "Berterima Kasih" },
    { unit: "Unit 5: Beradab Sopan dalam Masyarakat", standardContent: "5.0 Beradab Sopan dan Berbudi Pekerti Mulia dalam Masyarakat", value: "Hemah Tinggi" },
    { unit: "Unit 6: Menghormati Masyarakat", standardContent: "6.0 Menghormati Masyarakat", value: "Hormat" },
    { unit: "Unit 7: Menyayangi Masyarakat", standardContent: "7.0 Menyayangi Masyarakat", value: "Kasih Sayang" },
    { unit: "Unit 8: Bersikap Adil dalam Masyarakat", standardContent: "8.0 Bersikap Adil dalam Masyarakat", value: "Keadilan" },
    { unit: "Unit 9: Berani dalam Masyarakat", standardContent: "9.0 Berani dalam Masyarakat", value: "Keberanian" },
    { unit: "Unit 10: Jujur dalam Masyarakat", standardContent: "10.0 Jujur dalam Masyarakat", value: "Kejujuran" },
    { unit: "Unit 11: Rajin dalam Masyarakat", standardContent: "11.0 Rajin dalam Masyarakat", value: "Kerajinan" },
    { unit: "Unit 12: Kerjasama dalam Masyarakat", standardContent: "12.0 Kerjasama dalam Masyarakat", value: "Kerjasama" },
    { unit: "Unit 13: Kesederhanaan dalam Masyarakat", standardContent: "13.0 Kesederhanaan dalam Masyarakat", value: "Kesederhanaan" },
    { unit: "Unit 14: Toleransi dalam Masyarakat", standardContent: "14.0 Toleransi dalam Masyarakat", value: "Toleransi" }
  ],
  "Tahun 6": [
    { unit: "Unit 1: Amalan Ajaran Agama Demi Negara", standardContent: "1.0 Amalan Ajaran Agama atau Kepercayaan Demi Negara", value: "Kepercayaan kepada Tuhan" },
    { unit: "Unit 2: Bantuan Kepada Negara", standardContent: "2.0 Bantuan Kepada Negara", value: "Baik Hati" },
    { unit: "Unit 3: Tanggungjawab Sebagai Warganegara", standardContent: "3.0 Tanggungjawab Sebagai Warganegara", value: "Bertanggungjawab" },
    { unit: "Unit 4: Amalan Berterima Kasih Terhadap Negara", standardContent: "4.0 Amalan Berterima Kasih Terhadap Negara", value: "Berterima Kasih" },
    { unit: "Unit 5: Beradab Sopan Terhadap Negara", standardContent: "5.0 Beradab Sopan dan Berbudi Pekerti Mulia Terhadap Negara", value: "Hemah Tinggi" },
    { unit: "Unit 6: Menghormati Negara", standardContent: "6.0 Menghormati Negara", value: "Hormat" },
    { unit: "Unit 7: Menyayangi Negara", standardContent: "7.0 Menyayangi Negara", value: "Kasih Sayang" },
    { unit: "Unit 8: Bersikap Adil Terhadap Negara", standardContent: "8.0 Bersikap Adil Terhadap Negara", value: "Keadilan" },
    { unit: "Unit 9: Berani Mempertahankan Negara", standardContent: "9.0 Berani Mempertahankan Negara", value: "Keberanian" },
    { unit: "Unit 10: Jujur Terhadap Negara", standardContent: "10.0 Jujur Terhadap Negara", value: "Kejujuran" },
    { unit: "Unit 11: Rajin Demi Negara", standardContent: "11.0 Rajin Demi Negara", value: "Kerajinan" },
    { unit: "Unit 12: Kerjasama Demi Negara", standardContent: "12.0 Kerjasama Demi Negara", value: "Kerjasama" },
    { unit: "Unit 13: Kesederhanaan Demi Negara", standardContent: "13.0 Kesederhanaan Demi Negara", value: "Kesederhanaan" },
    { unit: "Unit 14: Toleransi Demi Negara", standardContent: "14.0 Toleransi Demi Negara", value: "Toleransi" }
  ],
  "Tingkatan 1": [
    { unit: "Bidang 1: Pengenalan Moral", standardContent: "1.1 Konsep Moral", value: "Rasional, Baik Hati, Bertanggungjawab" },
    { unit: "Bidang 1: Pengenalan Moral", standardContent: "1.2 Insan Bermoral", value: "Kepercayaan kepada Tuhan, Hemah Tinggi, Harga Diri" },
    { unit: "Bidang 1: Pengenalan Moral", standardContent: "1.3 Hidup Bermoral", value: "Toleransi, Kejujuran, Kerjasama" },
    { unit: "Bidang 2: Diri, Keluarga dan Persahabatan", standardContent: "2.1 Hidup Beragama atau Berkepercayaan", value: "Kepercayaan kepada Tuhan, Bertanggungjawab, Hormat" },
    { unit: "Bidang 2: Diri, Keluarga dan Persahabatan", standardContent: "2.2 Potensi Diri", value: "Kerajinan, Harga Diri, Hemah Tinggi" },
    { unit: "Bidang 2: Diri, Keluarga dan Persahabatan", standardContent: "2.3 Hubungan Kekeluargaan", value: "Kasih Sayang, Hormat, Bertanggungjawab" },
    { unit: "Bidang 2: Diri, Keluarga dan Persahabatan", standardContent: "2.4 Hubungan Persahabatan", value: "Toleransi, Kejujuran, Kerjasama" },
    { unit: "Bidang 3: Hubungan antara Diri, Komuniti dan Masyarakat", standardContent: "3.1 Kesejahteraan dalam Kalangan Warga Sekolah", value: "Toleransi, Kerjasama, Hormat" },
    { unit: "Bidang 3: Hubungan antara Diri, Komuniti dan Masyarakat", standardContent: "3.2 Keselamatan Kawasan Kediaman", value: "Bertanggungjawab, Berani, Kerjasama" },
    { unit: "Bidang 4: Moral, Peraturan dan Undang-undang", standardContent: "4.1 Etika Penggunaan Siber", value: "Bertanggungjawab, Harga Diri, Hemah Tinggi" },
    { unit: "Bidang 4: Moral, Peraturan dan Undang-undang", standardContent: "4.2 Keselamatan Jalan Raya", value: "Hormat, Bertanggungjawab, Toleransi" }
  ],
  "Tingkatan 2": [
    { unit: "Bidang 1: Pengenalan Moral", standardContent: "1.1 Sumber Moral", value: "Kepercayaan kepada Tuhan, Rasional, Toleransi" },
    { unit: "Bidang 2: Diri, Keluarga dan Persahabatan", standardContent: "2.1 Agama atau Kepercayaan Membentuk Keperibadian Diri", value: "Kepercayaan kepada Tuhan, Harga Diri, Hemah Tinggi" },
    { unit: "Bidang 2: Diri, Keluarga dan Persahabatan", standardContent: "2.2 Tanggungjawab Diri", value: "Bertanggungjawab, Berdikari, Kerajinan" },
    { unit: "Bidang 2: Diri, Keluarga dan Persahabatan", standardContent: "2.3 Tanggungjawab Diri dalam Keluarga", value: "Bertanggungjawab, Kasih Sayang, Hormat" },
    { unit: "Bidang 2: Diri, Keluarga dan Persahabatan", standardContent: "2.4 Adab Persahabatan", value: "Kebebasan, Kejujuran, Toleransi" },
    { unit: "Bidang 3: Hubungan antara Diri, Komuniti dan Masyarakat", standardContent: "3.1 Hidup Bermasyarakat", value: "Kerjasama, Toleransi, Hemah Tinggi" },
    { unit: "Bidang 3: Hubungan antara Diri, Komuniti dan Masyarakat", standardContent: "3.2 Pengekalan Amalan Tradisi Kekeluargaan", value: "Hormat, Kasih Sayang, Rasional" },
    { unit: "Bidang 3: Hubungan antara Diri, Komuniti dan Masyarakat", standardContent: "3.3 Konflik dalam Adab Persahabatan", value: "Kejujuran, Toleransi, Rasional" },
    { unit: "Bidang 4: Moral, Peraturan dan Undang-undang", standardContent: "4.1 Hak Tanggungjawab Pengguna", value: "Rasional, Keadilan, Keberanian" }
  ],
  "Tingkatan 3": [
    { unit: "Bidang 1: Pengenalan Moral", standardContent: "1.1 Pilihan Bermoral", value: "Kepercayaan kepada Tuhan, Kebebasan, Bertanggungjawab" },
    { unit: "Bidang 2: Diri, Keluarga dan Persahabatan", standardContent: "2.1 Anugerah Alam Ciptaan Tuhan", value: "Kepercayaan kepada Tuhan, Kasih Sayang, Rasional" },
    { unit: "Bidang 2: Diri, Keluarga dan Persahabatan", standardContent: "2.2 Kebestarian Diri", value: "Bertanggungjawab, Berdikari, Kerajinan" },
    { unit: "Bidang 2: Diri, Keluarga dan Persahabatan", standardContent: "2.3 Pengekalan Amalan Tradisi Kekeluargaan", value: "Hormat, Kasih Sayang, Rasional" },
    { unit: "Bidang 2: Diri, Keluarga dan Persahabatan", standardContent: "2.4 Konflik dalam Adab Persahabatan", value: "Kejujuran, Toleransi, Rasional" },
    { unit: "Bidang 3: Hubungan antara Diri, Komuniti dan Masyarakat", standardContent: "3.1 Hidup Bersatu Padu dalam Kepelbagaian Agama, Bangsa, Budaya dan Bahasa", value: "Toleransi, Hemah Tinggi, Rasional" },
    { unit: "Bidang 3: Hubungan antara Diri, Komuniti dan Masyarakat", standardContent: "3.2 Perkhidmatan Awam Pemangkin Pembangunan Negara", value: "Bertanggungjawab, Patriotisme, Berterima Kasih" },
    { unit: "Bidang 3: Hubungan antara Diri, Komuniti dan Masyarakat", standardContent: "3.3 5G dalam Kehidupan", value: "Rasional, Bertanggungjawab, Keberanian" },
    { unit: "Bidang 4: Moral, Peraturan dan Undang-undang", standardContent: "4.1 Hak dan Tanggungjawab Warganegara", value: "Bertanggungjawab, Patriotisme, Kebebasan" }
  ],
  "Tingkatan 4": [
    { unit: "Bidang 5: Insan Bermoral", standardContent: "5.1 Norma Masyarakat Pemangkin Kesejahteraan", value: "Hormat, Hemah Tinggi, Toleransi" },
    { unit: "Bidang 5: Insan Bermoral", standardContent: "5.2 Peribadi Mulia Hiasan Diri", value: "Kepercayaan kepada Tuhan, Hemah Tinggi, Harga Diri" },
    { unit: "Bidang 5: Insan Bermoral", standardContent: "5.3 Prinsip Keadilan dan Keprihatinan dalam Membuat Keputusan", value: "Rasional, Keadilan, Kasih Sayang" },
    { unit: "Bidang 5: Insan Bermoral", standardContent: "5.4 Penggunaan Teknologi Maklumat dan Komunikasi Secara Beretika", value: "Rasional, Kebebasan, Harga Diri" },
    { unit: "Bidang 6: Jati Diri Moral", standardContent: "6.1 Integriti Individu", value: "Kepercayaan kepada Tuhan, Kejujuran, Harga Diri" },
    { unit: "Bidang 6: Jati Diri Moral", standardContent: "6.2 Integriti Keluarga", value: "Kasih Sayang, Hormat, Toleransi" },
    { unit: "Bidang 6: Jati Diri Moral", standardContent: "6.3 Perikemanusiaan Pemangkin Kesejahteraan Global", value: "Kepercayaan kepada Tuhan, Baik Hati, Kasih Sayang" },
    { unit: "Bidang 7: Moral dan Kenegaraan", standardContent: "7.1 Hak dan Tanggungjawab Warganegara", value: "Bertanggungjawab, Patriotisme, Kebebasan" },
    { unit: "Bidang 7: Moral dan Kenegaraan", standardContent: "7.2 Perpaduan dalam Masyarakat", value: "Toleransi, Kerjasama, Hormat" },
    { unit: "Bidang 7: Moral dan Kenegaraan", standardContent: "7.3 Pengurusan Perbelanjaan Secara Beretika", value: "Kesederhanaan, Bertanggungjawab, Berdikari" }
  ],
  "Tingkatan 5": [
    { unit: "Bidang 5: Insan Bermoral", standardContent: "5.1 Norma Masyarakat Global", value: "Hormat, Hemah Tinggi, Rasional" },
    { unit: "Bidang 5: Insan Bermoral", standardContent: "5.2 Individu Glokal", value: "Kepercayaan kepada Tuhan, Hemah Tinggi, Harga Diri" },
    { unit: "Bidang 5: Insan Bermoral", standardContent: "5.3 Kerohanian Membentuk Individu Bermoral", value: "Kepercayaan kepada Tuhan, Kasih Sayang, Bertanggungjawab" },
    { unit: "Bidang 5: Insan Bermoral", standardContent: "5.4 Penggunaan Sumber dan Penyebaran Maklumat demi Kesejahteraan Sejagat", value: "Rasional, Kebebasan, Kejujuran" },
    { unit: "Bidang 6: Jati Diri Moral", standardContent: "6.1 Integriti Organisasi", value: "Kejujuran, Kerjasama, Bertanggungjawab" },
    { unit: "Bidang 6: Jati Diri Moral", standardContent: "6.2 Integriti demi Pembangunan Negara", value: "Kejujuran, Patriotisme, Bertanggungjawab" },
    { unit: "Bidang 6: Jati Diri Moral", standardContent: "6.3 Perikemanusiaan Pemangkin Kesejahteraan Global", value: "Kepercayaan kepada Tuhan, Baik Hati, Kasih Sayang" },
    { unit: "Bidang 7: Moral dan Kenegaraan", standardContent: "7.1 Penglibatan Diri dalam Program Komuniti", value: "Kerjasama, Baik Hati, Bertanggungjawab" },
    { unit: "Bidang 7: Moral dan Kenegaraan", standardContent: "7.2 Penglibatan Diri dalam Pembangunan Negara", value: "Patriotisme, Kerajinan, Bertanggungjawab" },
    { unit: "Bidang 7: Moral dan Kenegaraan", standardContent: "7.3 Hubungan Antarabangsa Menjamin Kesejahteraan Sejagat", value: "Hormat, Toleransi, Kerjasama" }
  ]
};
